# Generated by Django 4.1.5 on 2023-01-31 10:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('baykeShop', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='baykeshopspu',
            name='img',
        ),
        migrations.RemoveField(
            model_name='baykeshopspu',
            name='target_url',
        ),
    ]
