# Generated by Django 4.1.5 on 2023-02-01 03:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('baykeShop', '0002_remove_baykeshopspu_img_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='baykeshopcategory',
            options={'verbose_name': '商品分类', 'verbose_name_plural': '商品分类'},
        ),
        migrations.AlterModelOptions(
            name='baykeshopspu',
            options={'verbose_name': '商品管理', 'verbose_name_plural': '商品管理'},
        ),
    ]
