# Generated by Django 4.1.5 on 2023-02-01 03:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('baykeShop', '0003_alter_baykeshopcategory_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='baykeshopspec',
            name='group',
        ),
    ]
