# Generated by Django 4.1.5 on 2023-02-02 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baykeShop', '0005_alter_baykeshopspec_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='baykeshopcategory',
            name='is_home',
            field=models.BooleanField(default=False, help_text='如果为True则推荐到首页楼层及出现在导航菜单', verbose_name='是否推荐'),
        ),
    ]
