# Generated by Django 4.1.5 on 2023-02-02 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baykeShop', '0006_baykeshopcategory_is_home'),
    ]

    operations = [
        migrations.AlterField(
            model_name='baykeshopcategory',
            name='img_map',
            field=models.ImageField(blank=True, help_text='图片尺寸为600 X 480', max_length=200, null=True, upload_to='category/imgMap/%Y', verbose_name='推荐图'),
        ),
    ]
