# Generated by Django 4.1.5 on 2023-02-02 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baykeShop', '0007_alter_baykeshopcategory_img_map'),
    ]

    operations = [
        migrations.AlterField(
            model_name='baykeshopsku',
            name='cover_pic',
            field=models.ImageField(blank=True, max_length=200, null=True, upload_to='cover/sku/%Y/%m', verbose_name='封面图'),
        ),
    ]
