# Generated by Django 4.1.5 on 2023-02-08 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baykeShop', '0010_alter_baykeshopsku_sales'),
    ]

    operations = [
        migrations.CreateModel(
            name='BaykeShopBanner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('add_date', models.DateTimeField(auto_now_add=True, verbose_name='添加时间')),
                ('pub_date', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('is_del', models.BooleanField(default=False, editable=False, verbose_name='删除')),
                ('img', models.ImageField(max_length=200, upload_to='Carousel/%Y/%m', verbose_name='轮播图')),
                ('target_url', models.CharField(blank=True, default='', max_length=200, verbose_name='跳转链接')),
                ('desc', models.CharField(blank=True, default='', max_length=150, verbose_name='描述')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
