# Generated by Django 4.1.5 on 2023-02-08 12:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('baykeShop', '0011_baykeshopbanner'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BaykeShopSpecGroup',
        ),
        migrations.AlterModelOptions(
            name='baykeshopbanner',
            options={'verbose_name': '轮播图管理', 'verbose_name_plural': '轮播图管理'},
        ),
        migrations.AlterField(
            model_name='baykeshopcategory',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='baykeShop.baykeshopcategory'),
        ),
        migrations.AlterField(
            model_name='baykeshopsku',
            name='spu',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='baykeShop.baykeshopspu', verbose_name='商品'),
        ),
        migrations.AlterField(
            model_name='baykeshopspecoption',
            name='spec',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='baykeShop.baykeshopspec', verbose_name='规格'),
        ),
        migrations.AlterField(
            model_name='baykespucarousel',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='baykeShop.baykeshopspu'),
        ),
    ]
