# Generated by Django 4.1.5 on 2023-02-10 03:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('baykeShop', '0015_baykeshopaddress_baykeshopaddress_unique_happy_addr'),
    ]

    operations = [
        migrations.CreateModel(
            name='BaykeUserInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('add_date', models.DateTimeField(auto_now_add=True, verbose_name='添加时间')),
                ('pub_date', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('is_del', models.BooleanField(default=False, editable=False, verbose_name='删除')),
                ('avatar', models.ImageField(blank=True, max_length=200, null=True, upload_to='avatar/%Y/%m', verbose_name='头像')),
                ('nickname', models.CharField(blank=True, default='', max_length=30, verbose_name='昵称')),
                ('phone', models.CharField(blank=True, default='', max_length=11, verbose_name='手机号')),
                ('balance', models.DecimalField(decimal_places=2, default=0.0, max_digits=8, verbose_name='余额')),
                ('owner', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': '用户',
                'verbose_name_plural': '用户',
            },
        ),
    ]
