# Generated by Django 4.1.5 on 2023-02-10 03:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baykeShop', '0016_baykeuserinfo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='baykeuserinfo',
            name='avatar',
            field=models.ImageField(blank=True, default='avatar/default.jpg', max_length=200, upload_to='avatar/%Y/%m', verbose_name='头像'),
        ),
    ]
