# Generated by Django 4.1.5 on 2023-02-13 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baykeShop', '0019_baykeshoporderinfo_baykeshopordersku'),
    ]

    operations = [
        migrations.AlterField(
            model_name='baykeshoporderinfo',
            name='address',
            field=models.CharField(max_length=200, verbose_name='地址'),
        ),
        migrations.AlterField(
            model_name='baykeshoporderinfo',
            name='freight',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=12, verbose_name='运费'),
        ),
    ]
