# Generated by Django 4.1.5 on 2023-02-13 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baykeShop', '0020_alter_baykeshoporderinfo_address_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='baykeshopordersku',
            name='desc',
            field=models.CharField(blank=True, default='', max_length=200, verbose_name='商品说明'),
        ),
    ]
