# Generated by Django 4.1.5 on 2023-02-14 01:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baykeShop', '0021_baykeshopordersku_desc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='baykeshoporderinfo',
            name='order_sn',
            field=models.CharField(blank=True, default='', editable=False, help_text='订单号', max_length=32, unique=True, verbose_name='订单号'),
        ),
        migrations.AlterField(
            model_name='baykeshoporderinfo',
            name='pay_method',
            field=models.IntegerField(blank=True, choices=[(1, '货到付款'), (2, '支付宝'), (3, '微信支付'), (4, '余额支付')], help_text='支付方式', null=True, verbose_name='支付方式'),
        ),
        migrations.AlterField(
            model_name='baykeshoporderinfo',
            name='trade_sn',
            field=models.CharField(blank=True, editable=False, help_text='交易号', max_length=64, null=True, unique=True, verbose_name='交易号'),
        ),
    ]
