# Generated by Django 4.1.5 on 2023-02-14 01:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('baykeShop', '0022_alter_baykeshoporderinfo_order_sn_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='baykeshoporderinfo',
            name='owner',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='用户'),
        ),
        migrations.AlterField(
            model_name='baykeshopordersku',
            name='order',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, to='baykeShop.baykeshoporderinfo', verbose_name='订单'),
        ),
        migrations.AlterField(
            model_name='baykeshopordersku',
            name='sku',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, to='baykeShop.baykeshopsku', verbose_name='订单商品'),
        ),
    ]
