# Generated by Django 4.1.5 on 2023-02-14 01:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baykeShop', '0023_alter_baykeshoporderinfo_owner_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='baykeshoporderinfo',
            name='pay_time',
            field=models.DateTimeField(blank=True, editable=False, help_text='支付时间', null=True, verbose_name='支付时间'),
        ),
    ]
