# Generated by Django 4.1.5 on 2023-02-15 01:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baykeShop', '0024_alter_baykeshoporderinfo_pay_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='baykeshoporderinfo',
            name='pay_method',
            field=models.IntegerField(blank=True, choices=[(1, '货到付款'), (2, '支付宝'), (3, '微信支付'), (4, '余额支付')], editable=False, help_text='支付方式', null=True, verbose_name='支付方式'),
        ),
    ]
