# Generated by Django 4.1.5 on 2023-02-15 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baykeShop', '0025_alter_baykeshoporderinfo_pay_method'),
    ]

    operations = [
        migrations.AlterField(
            model_name='baykeuserinfo',
            name='avatar',
            field=models.ImageField(blank=True, default='avatar/default.jpg', max_length=200, upload_to='avatar/', verbose_name='头像'),
        ),
    ]
