# Generated by Django 4.1.5 on 2023-02-16 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baykeShop', '0032_baykeuserbalancelog_change_way_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='baykeuserinfo',
            name='phone',
            field=models.CharField(blank=True, max_length=11, null=True, unique=True, verbose_name='手机号'),
        ),
    ]
