# Generated by Django 4.1.5 on 2023-02-17 03:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baykeShop', '0033_alter_baykeuserinfo_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='baykeshopordersku',
            name='content',
            field=models.TextField(blank=True, default='', verbose_name='商品详情'),
        ),
        migrations.AddField(
            model_name='baykeshopordersku',
            name='spec',
            field=models.CharField(blank=True, default='', max_length=200, verbose_name='商品规格'),
        ),
        migrations.AddField(
            model_name='baykeshopordersku',
            name='title',
            field=models.CharField(blank=True, default='', max_length=200, verbose_name='商品标题'),
        ),
    ]
