# Generated by Django 4.1.5 on 2023-02-18 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baykeShop', '0035_baykeshoporderskucomment'),
    ]

    operations = [
        migrations.AddField(
            model_name='baykeshopordersku',
            name='is_commented',
            field=models.BooleanField(default=False, verbose_name='是否已评价'),
        ),
    ]
