# Generated by Django 4.1.7 on 2023-03-20 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baykeshop', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='baykeuserinfo',
            name='desc',
            field=models.CharField(blank=True, default='', max_length=150, verbose_name='描述'),
        ),
    ]
