# Generated by Django 4.1.7 on 2023-03-27 08:03

import baykeshop.public.tinymce
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('baykeshop', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='baykearticle',
            name='content',
            field=baykeshop.public.tinymce.TinymceField(tinymce={'plugins': 'code'}, verbose_name='内容'),
        ),
    ]
