# Generated by Django 4.1.7 on 2023-03-27 08:04

import baykeshop.public.tinymce
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('baykeshop', '0002_alter_baykearticle_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='baykearticle',
            name='content',
            field=baykeshop.public.tinymce.TinymceField(tinymce={'plugins': ['advlist', 'autolink', 'link', 'image', 'lists', 'charmap', 'preview', 'anchor', 'pagebreak', 'searchreplace', 'wordcount', 'visualblocks', 'visualchars', 'code', 'fullscreen', 'insertdatetime', 'media', 'table', 'emoticons', 'template', 'help']}, verbose_name='内容'),
        ),
    ]
