# Generated by Django 4.1.7 on 2023-02-23 04:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('baykeshop', '0002_alter_baykebanner_is_del_alter_baykemenu_is_del_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='baykepermission',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='baykepermission',
            name='url',
            field=models.CharField(blank=True, default='', max_length=150, verbose_name='url'),
        ),
        migrations.AlterField(
            model_name='baykepermission',
            name='icon',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='baykepermission',
            name='permission',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='auth.permission', verbose_name='权限'),
        ),
    ]
