# Generated by Django 4.1.7 on 2023-03-22 02:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('baykeshop', '0002_baykeuserinfo_desc'),
    ]

    operations = [
        migrations.CreateModel(
            name='BaykeIPAddress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('add_date', models.DateTimeField(auto_now_add=True)),
                ('pub_date', models.DateTimeField(auto_now=True)),
                ('is_del', models.BooleanField(default=False, editable=False)),
                ('ip', models.GenericIPAddressField(blank=True, null=True)),
                ('browser', models.CharField(blank=True, default='', max_length=150)),
                ('address', models.CharField(blank=True, default='', max_length=150)),
            ],
            options={
                'verbose_name': 'BaykeStatsIPAddress',
                'verbose_name_plural': 'BaykeStatsIPAddress',
            },
        ),
        migrations.CreateModel(
            name='BaykeStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('add_date', models.DateTimeField(auto_now_add=True)),
                ('pub_date', models.DateTimeField(auto_now=True)),
                ('is_del', models.BooleanField(default=False, editable=False)),
                ('object_id', models.PositiveIntegerField()),
                ('pv', models.BigIntegerField(default=0)),
                ('uv', models.BigIntegerField(default=0)),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
            ],
            options={
                'verbose_name': 'BaykeStats',
                'verbose_name_plural': 'BaykeStatss',
            },
        ),
    ]
