# Generated by Django 4.1.7 on 2023-02-24 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baykeshop', '0003_baykepermission_owner_baykepermission_url_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='baykepermission',
            name='owner',
        ),
        migrations.AlterField(
            model_name='baykeshoporderskucomment',
            name='comment_choices',
            field=models.PositiveSmallIntegerField(choices=[(5, '好评'), (3, '中评'), (1, '差评')], default=5, verbose_name='评分'),
        ),
    ]
