# Generated by Django 4.1.7 on 2023-03-22 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baykeshop', '0004_alter_baykeipaddress_browser'),
    ]

    operations = [
        migrations.AlterField(
            model_name='baykeipaddress',
            name='browser',
            field=models.TextField(blank=True, default='', max_length=500),
        ),
    ]
