# Generated by Django 4.1.7 on 2023-02-25 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baykeshop', '0004_remove_baykepermission_owner_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='baykepermission',
            name='is_show',
            field=models.BooleanField(default=True),
        ),
    ]
