# Generated by Django 4.1.7 on 2023-02-28 03:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baykeshop', '0005_baykepermission_is_show'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='baykemenu',
            options={'ordering': ['-sort'], 'verbose_name': '菜单', 'verbose_name_plural': '菜单'},
        ),
        migrations.AlterModelOptions(
            name='baykepermission',
            options={'verbose_name': '菜单', 'verbose_name_plural': '菜单'},
        ),
        migrations.AlterField(
            model_name='baykemenu',
            name='name',
            field=models.CharField(max_length=50, unique=True, verbose_name='菜单名称'),
        ),
        migrations.AlterField(
            model_name='baykemenu',
            name='sort',
            field=models.PositiveSmallIntegerField(default=1, verbose_name='排序'),
        ),
        migrations.AlterField(
            model_name='baykepermission',
            name='url',
            field=models.CharField(blank=True, default='', editable=False, max_length=150, verbose_name='url'),
        ),
    ]
