# Generated by Django 4.1.7 on 2023-02-28 13:11

from django.db import migrations, models
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('baykeshop', '0006_alter_baykemenu_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BaykeUpload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('add_date', models.DateTimeField(auto_now_add=True)),
                ('pub_date', models.DateTimeField(auto_now=True)),
                ('is_del', models.BooleanField(default=False, editable=False)),
                ('img', models.ImageField(max_length=200, upload_to='upload/editor/')),
            ],
            options={
                'verbose_name': '富文本编辑器图片上传',
                'verbose_name_plural': '富文本编辑器图片上传',
            },
        ),
        migrations.AlterField(
            model_name='baykeshopspu',
            name='content',
            field=tinymce.models.HTMLField(verbose_name='商品详情'),
        ),
    ]
