# Generated by Django 4.1.7 on 2023-03-12 12:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('baykeshop', '0006_baykeshoporderinfo_baykeshopordersku'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='baykeshoporderinfo',
            name='freight',
        ),
    ]
