# Generated by Django 4.1.7 on 2023-02-28 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baykeshop', '0007_baykeupload_alter_baykeshopspu_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='baykeshopspu',
            name='content',
            field=models.TextField(verbose_name='商品详情'),
        ),
    ]
