# Generated by Django 4.1.7 on 2023-03-15 01:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('baykeshop', '0007_remove_baykeshoporderinfo_freight'),
    ]

    operations = [
        migrations.CreateModel(
            name='BaykeOrderInfoComments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('add_date', models.DateTimeField(auto_now_add=True)),
                ('pub_date', models.DateTimeField(auto_now=True)),
                ('is_del', models.BooleanField(default=False, editable=False)),
                ('object_id', models.PositiveIntegerField()),
                ('content', models.CharField(max_length=200, verbose_name='留言内容')),
                ('comment_choices', models.PositiveSmallIntegerField(choices=[(5, '好评'), (3, '中评'), (1, '差评')], default=5, verbose_name='评分')),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': '商品评价',
                'verbose_name_plural': '商品评价',
                'ordering': ['-add_date'],
                'abstract': False,
            },
        ),
        migrations.AddIndex(
            model_name='baykeorderinfocomments',
            index=models.Index(fields=['content_type', 'object_id'], name='baykeshop_b_content_386eed_idx'),
        ),
    ]
