# Generated by Django 4.1.7 on 2023-03-16 02:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('baykeshop', '0008_baykeorderinfocomments_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='baykepermission',
            options={'verbose_name': '菜单权限', 'verbose_name_plural': '菜单权限'},
        ),
    ]
