# Generated by Django 4.1.7 on 2023-03-16 02:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('baykeshop', '0009_alter_baykepermission_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='baykeshopordersku',
            name='order',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to='baykeshop.baykeshoporderinfo', verbose_name='订单'),
        ),
    ]
