# Generated by Django 4.1.7 on 2023-03-16 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baykeshop', '0010_alter_baykeshopordersku_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='baykeshopsku',
            name='cover_pic',
            field=models.ImageField(default=1, max_length=200, upload_to='cover/sku/%Y/%m', verbose_name='封面图'),
            preserve_default=False,
        ),
    ]
