# Generated by Django 4.1.5 on 2023-01-31 08:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('baykeAdmin', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='baykemenu',
            name='parent',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, to='baykeAdmin.baykemenu'),
        ),
    ]
