# Generated by Django 4.1.5 on 2023-01-31 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baykeAdmin', '0002_alter_baykemenu_parent'),
    ]

    operations = [
        migrations.AddField(
            model_name='baykemenu',
            name='sort',
            field=models.PositiveSmallIntegerField(default=1),
        ),
    ]
