# Generated by Django 4.1.5 on 2023-02-01 03:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('baykeAdmin', '0003_baykemenu_sort'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='baykemenu',
            options={'ordering': ['-sort'], 'verbose_name': 'BaykeMenu', 'verbose_name_plural': 'BaykeMenus'},
        ),
        migrations.AlterModelOptions(
            name='baykepermission',
            options={'verbose_name': '权限规则', 'verbose_name_plural': '权限规则'},
        ),
    ]
